import type { Metadata } from "next";
import { IBM_Plex_Mono, Figtree } from "next/font/google";
import "./globals.css";
import Providers from "@/context/Providers";

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans",
  display: "swap",
});

const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} ${plexMono.variable} antialiased w-full max-w-400 mx-auto`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}