import type { Metadata } from "next";
import { IBM_Plex_Mono, Figtree, Geist } from "next/font/google";
import "./globals.css";
import Providers from "@/context/Providers";
import BackgroundGrid from "@/components/shared/BackgroundGrid";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${geist.variable} ${plexMono.variable} antialiased w-full max-w-400 mx-auto`}
      >
        <Providers>
          <BackgroundGrid />
          {children}
        </Providers>
      </body>
    </html>
  );
}
