import type { Metadata } from "next";
import { IBM_Plex_Mono, Figtree } from "next/font/google";
import "./globals.css";
import Providers from "@/context/Providers";
import BackgroundGrid from "@/components/shared/BackgroundGrid";
import { Toaster } from "sonner";

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans",
  display: "swap",
});

const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} ${plexMono.variable} antialiased w-full max-w-400 mx-auto`}
      >
        <Providers>
          <BackgroundGrid />
          <Toaster
            position="top-center"
            richColors
            toastOptions={{
              className:
                "font-mono text-[12px] border border-(--border) bg-(--surface) text-(--text)",
            }} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
